### PR TITLE
Profiler utility

### PR DESCRIPTION
**Pull request by nkrusch**
Fixed the timeout, I think, because it works now on the build server.

### CODE REVIEW

**Comment by aubertc** [comment]
> [18:43:52]: dense             ... timeout: 10.01s

It worked ;-)

**Comment by aubertc** [comment]
Sorry, I take it back: it _displayed_ the timeout but I believe the process kept running and eventually froze my computer (so that I couldn't make sure it was actually the reason). I'll try to debug that locally.

**Comment by nkrusch** [comment]
Hmm okay. I have the following comments regarding this

1. dense still remains un-analyzable at this time, unfortunately, and trying to analyze it freezes at my end also. Maybe should add some warning about it where we list examples?
2. For this profiler tool, I have added an option to skip specific examples:  `python utilities/profiler.py --skip dense`
3. I'm still not sure why it does not kill the subprocess, and I'm unable to reproduce locally. I've narrowed down the issue here:

https://github.com/seiller/pymwp/blob/7ce88836bff9283ed6a8b1b28306ad5252c2100d/utilities/profiler.py#L160-L162

4. I now run this [profiler on a schedule automatically](https://github.com/seiller/pymwp/actions/workflows/profile.yaml)

**Comment by seiller** [comment]
Hi! For item 1., is this true for the delta_graph branch as well? (I mean if we just answer either yes or no and avoid computing all the evaluations.)

**Comment by nkrusch** [comment]
Hi Thomas, I have not tried delta_graph yet. Is it ready to merge? If it is ready, we should merge it to master and hopefully that resolves item 1.

**Comment by seiller** [comment]
Hi,

I do not know if it is ready to merge (I think w were close two week ago); I have been busy with other things this week. Thomas R will know.

Best,
/t

**Comment by ThomasRuby** [comment]
The branch with "regexp" is better than the one without, it computes faster the complementary choices (aka not in the delta_graph).
I've commented : https://github.com/seiller/pymwp/commit/5edf5f20a25bf13862ac609a4189d412ac09689a#commitcomment-52153489
> for me, python killed the process on `dense.c` ^^' but it seems as fast as `simpl` for `not_infinite_8.c` maybe it means that for bigger example, the filtering is worth ? (in time but not in space ^^')
> The reality is that we have more combinations than the list max size in python. And I think it's still true after the filtering. So even if we can produce only the complementary combinations, it will always be too large.

So it can be merged (maybe after a rebase would be easier…) but it does not help for `dense.c` I'm scared :/

**Comment by ThomasRuby** [comment]
> The branch with "regexp" is better than the one without, it computes faster the complementary choices (aka not in the delta_graph).
> I've commented : [5edf5f2#commitcomment-52153489](https://github.com/seiller/pymwp/commit/5edf5f20a25bf13862ac609a4189d412ac09689a#commitcomment-52153489)
> 
> > for me, python killed the process on `dense.c` ^^' but it seems as fast as `simpl` for `not_infinite_8.c` maybe it means that for bigger example, the filtering is worth ? (in time but not in space ^^')
> > The reality is that we have more combinations than the list max size in python. And I think it's still true after the filtering. So even if we can produce only the complementary combinations, it will always be too large.
> 
> So it can be merged (maybe after a rebase would be easier…) but it does not help for `dense.c` I'm scared :/

I didn't precise but here it takes all combinations and removes the ones that match choices in `delta_graph` using regular expressions.

**Comment by seiller** [comment]
Yes, that's an important precision. The ideal way would be to generate only the correct assignments instead of generating all possible ones and then remove incorrect ones. At the risk of repeating myself, maybe a clever use of iter could be used (in an ideal world we could use regular expressions to generate subsets of iter in an efficient way).

**Comment by ThomasRuby** [comment]
I feel it's way more complicated to generate only the good ones instead of removing the bad ones. But here I think we can maybe correct the "list max size" problem… The issue is that I'm writing all combinations in one string to use a regexp to match all infinite choices and remove them. But apparently it's a too long to fit in a string ^^' maybe @nkrusch has some idea to deal with that ?
Maybe using buffer or similar stuff ?

**Comment by seiller** [comment]
I understand it is more complicated, but it should be more efficient! We should try to find a way to do it. Suppose we've computed the complement, then all we need is to generate the assignments that "coincide" with the lists of deltas in the delta_graph (i.e. the list describes a cylinder -- a basic open set -- in the product space, i.e. delta(1,4)delta(2,7) describes all assignments for which the 4th element is a 1, and the 7th element is a 2). So one simple idea is to start from the lowest layers and generate all assignments like this: take a list of deltas and create all the assignments that satisfy it; we can use iter in some way (since it is efficient), as for all indices not appearing in the deltas (i.e. the 4 and 7 in the above example) we want to generate the product space. (In fact, the best way may be to define a new data structure mixing iter and lists of deltas to describe assignments; it may be interesting to discuss this in more details.) This should work well (i.e. not produce the same assignment twice) because of the simplification rule.

**Comment by seiller** [comment]
(note that "lowest level" means we start with the smallest lists here)

**Comment by nkrusch** [comment]
If we are exceeding [capacity of string](https://stackoverflow.com/a/67446043) I would think we should try to find a better strategy to handle the problem, over a better way to fit the data.

**Pull request merged**
