### PR TITLE
Add tools for profiling

### PR DESCRIPTION
**Pull request by nkrusch**
This PR adds a utility for running cProfile on multiple examples. I have added docs to explain how to use it.

When I run on GH server (linux) the dense function hangs, but it should timeout after 30 sec. It terminates correctly for me. Please try it and let me know if it gets stuck on all Linux machines or just the build machine, I'm not sure.

### CODE REVIEW

**Review by aubertc — COMMENTED** [review]
I got:
```
make profile
test -d venv || python3 -m venv venv;
source venv/bin/activate;
pip3 install -q -r requirements-dev.txt
python3 utilities/profile.py
==================================================
Profiling 48 C files...
==================================================
[13:56:43]: aplas_example1    ... done : 0.18s
[13:56:43]: aplas_example2    ... done : 0.13s
[13:56:43]: assign_expression ... done : 0.11s
[13:56:43]: assign_value      ... done : 0.11s
[13:56:43]: assign_variable   ... done : 0.11s
[13:56:44]: declaration       ... done : 0.11s
[13:56:44]: empty             ... done : 0.10s
[13:56:44]: empty_main        ... done : 0.10s
[13:56:44]: if                ... done : 0.11s
[13:56:44]: if_else           ... done : 0.11s
[13:56:44]: while_1           ... done : 0.11s
[13:56:44]: while_2           ... done : 0.11s
[13:56:44]: while_if          ... done : 0.11s
[13:56:45]: composition_inline... done : 0.16s
[13:56:45]: exponent_1        ... done : 0.12s
[13:56:45]: exponent_2        ... done : 0.12s
[13:56:45]: infinite_2        ... done : 0.14s
[13:56:45]: infinite_3        ... done : 0.12s
[13:56:49]: infinite_4        ... done : 3.80s
[13:56:50]: infinite_5        ... done : 0.89s
[13:56:52]: infinite_6        ... done : 1.54s
[13:56:53]: infinite_7        ... done : 1.14s
[13:56:54]: infinite_8        ... done : 1.36s
[13:56:54]: notinfinite_2     ... done : 0.11s
[13:56:54]: notinfinite_3     ... done : 0.15s
[13:56:55]: notinfinite_4     ... done : 0.18s
[13:56:55]: notinfinite_5     ... done : 0.18s
[13:56:55]: notinfinite_6     ... done : 0.18s
[13:56:56]: notinfinite_7     ... done : 0.97s
[13:56:57]: notinfinite_8     ... done : 1.50s
[13:56:58]: example3_1_a      ... done : 0.11s
[13:56:58]: example3_1_b      ... done : 0.11s
[13:56:58]: example3_1_c      ... done : 0.11s
[13:56:58]: example3_1_d      ... done : 0.11s
[13:56:58]: example3_2        ... done : 0.11s
[13:56:58]: example3_4        ... done : 0.13s
[13:56:58]: example5_1        ... done : 0.11s
[13:56:59]: example7_10       ... done : 0.11s
[13:56:59]: example7_11       ... done : 0.12s
[13:56:59]: braces_issues     ... done : 0.11s
[13:59:35]: dense             ... timeout : 156.00s
[13:59:36]: explosion         ... done : 1.60s
[13:59:37]: f_alone           ... done : 0.19s
[13:59:37]: f_inline          ... done : 0.14s
[13:59:37]: f_main            ... done : 0.12s
[13:59:37]: for_body          ... error : 0.17s
[13:59:37]: for_not_body      ... done : 0.12s
[13:59:37]: temp              ... done : 0.13s
==================================================
Finished after 174.75 seconds.
==================================================

```

**Comment by nkrusch** [comment]
hmmm ok. The timeout should be 30 s, but at least it did eventually terminate. thanks. Overall "it works" (sort of) how it is supposed to.

**Comment by aubertc** [comment]
Dense.c just crashed my computer. There is no "built-in" timeout, correct?

**Comment by nkrusch** [comment]
There should be but for some reasons it seems to not apply on Linux. I'm not sure why.

It runs by spawning a new subprocess and if that subprocess does not terminate within timeout, parent is supposed to terminate the subprocess.

BTW the way to read that output is: 

- done = process exited, could have existed with non-0 since empty.c does that, but it does not throw 
- error = this example throws an error if you try to analyze it
- timeout = does not terminate

and the time is how long it took for that example.

**Pull request merged**
